# TODO: Fix rubocop not cover all files
AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Include:
    - Rakefile
    - config.ru
    - config/initializer/*
  Exclude:
    - db/**/*
    - bin/*
    - config/**/*
    - vendor/ruby/**/*
    - vendor/bundle/**/*
    - node_modules/**/*
Rails:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - spec/support/*
    - Guardfile
Naming/FileName:
  Exclude:
    - Gemfile
    - Guardfile
    - Capfile
Style/Documentation:
  Enabled: false
