# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a4f7fb594c74822eac87ea268d15785e9b28bd14a330354889f50522ddf3ba67adb711ef05413171b3ed8f8148186df9ef0e16b02b52d49b88788ed9bb8ca457

test:
  secret_key_base: 4b8a5c32ef174f4b0071052a2d64eacfe1a0e8ea17fa7111254af29bf51415bd4d5e32bdcefba1413019bff968b394f6c844e315c1c07af99103dcbe33208ae0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
